// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
)

type Class struct {
	ID    int64
	Class string
}

type Resrecord struct {
	ID      int64
	Domain  string
	Data    string
	Typeid  int64
	Classid int64
	Ttl     sql.NullInt64
}

type ResrecordsClass struct {
	Classid     int64
	Resrecordid int64
}

type ResrecordsType struct {
	Typeid      int64
	Resrecordid int64
}

type Type struct {
	ID   int64
	Type string
}
