// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Resourcerecord struct {
	ID     int64
	Domain string
	Result string
	Type   string
	Class  string
	Ttl    sql.NullInt64
}
