// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID    int32  `db:"id" json:"id"`
	Class string `db:"class" json:"class"`
}

type ResourceRecord struct {
	ID         int32       `db:"id" json:"id"`
	Domain     string      `db:"domain" json:"domain"`
	Data       string      `db:"data" json:"data"`
	TypeID     int32       `db:"type_id" json:"type_id"`
	ClassID    int32       `db:"class_id" json:"class_id"`
	TimeToLive pgtype.Int4 `db:"time_to_live" json:"time_to_live"`
}

type Role struct {
	ID   int32  `db:"id" json:"id"`
	Role string `db:"role" json:"role"`
}

type Type struct {
	ID   int32  `db:"id" json:"id"`
	Type string `db:"type" json:"type"`
}

type User struct {
	ID        int32       `db:"id" json:"id"`
	Login     string      `db:"login" json:"login"`
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Password  string      `db:"password" json:"password"`
	RoleID    pgtype.Int4 `db:"role_id" json:"role_id"`
}
